create database College;
CREATE DATABASE IF NOT EXISTS COLLEGE;

DROP DATABASE IF EXISTS COMPANY;
USE College;
CREATE TABLE Student(
	id int PRIMARY KEY,
	NAME varchar(50),
    AGE INT NOT NULL
);
DROP TABLE student;

INSERT INTO student VALUES(1, "SWEATA", 21);
INSERT INTO student VALUES(2, "RAHUL", 20);

SELECT * FROM student;
SHOW DATABASES;
SHOW TABLES;

CREATE TABLE CLASS(
	rollno INT PRIMARY KEY,
    NAME VARCHAR(50)
) ;
INSERT INTO CLASS
(rollno, NAME)
VALUES
(143, "SWEATA");
(171, "RAHUL");

SELECT * FROM CLASS;
SHOW TABLES;
